// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taxes.Infrastructure;
using Taxes.Infrastructure.Persistence;

#nullable disable

namespace Taxes.Infrastructure.Migrations
{
    [DbContext(typeof(TaxDbContext))]
    [Migration("20240218203533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Taxes.Domain.Models.Tax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "City" }, "Index_City");

                    b.ToTable("Taxes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fea10830-70ad-4ae6-9ed8-b9f53763cb3a"),
                            Category = 1,
                            City = "Kaunas",
                            CreatedAt = new DateTime(2024, 2, 18, 20, 35, 32, 880, DateTimeKind.Utc).AddTicks(4110),
                            Rate = 3.3m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e0b8e34e-dc33-4d3b-b73e-ed899bf584f8"),
                            Category = 2,
                            City = "Kaunas",
                            CreatedAt = new DateTime(2024, 2, 18, 20, 35, 32, 880, DateTimeKind.Utc).AddTicks(4120),
                            Rate = 5m,
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0b9429e3-bc68-48c7-b69e-cdc49bc2823f"),
                            Category = 2,
                            City = "Kaunas",
                            CreatedAt = new DateTime(2024, 2, 18, 20, 35, 32, 880, DateTimeKind.Utc).AddTicks(4130),
                            Rate = 4m,
                            StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2b103a0d-2eb7-4094-b455-37f23892c7a8"),
                            Category = 2,
                            City = "Kaunas",
                            CreatedAt = new DateTime(2024, 2, 18, 20, 35, 32, 880, DateTimeKind.Utc).AddTicks(4130),
                            Rate = 6m,
                            StartDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2362d6ae-f2f9-4eb2-ab3c-5d5e9cabc185"),
                            Category = 3,
                            City = "Kaunas",
                            CreatedAt = new DateTime(2024, 2, 18, 20, 35, 32, 880, DateTimeKind.Utc).AddTicks(4130),
                            Rate = 2.5m,
                            StartDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("69c96c48-4ba0-435b-842c-1b55d35aa79c"),
                            Category = 3,
                            City = "Kaunas",
                            CreatedAt = new DateTime(2024, 2, 18, 20, 35, 32, 880, DateTimeKind.Utc).AddTicks(4140),
                            Rate = 2.5m,
                            StartDate = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("79dd5c83-166f-496c-b5c7-0d9932c387c8"),
                            Category = 4,
                            City = "Kaunas",
                            CreatedAt = new DateTime(2024, 2, 18, 20, 35, 32, 880, DateTimeKind.Utc).AddTicks(4140),
                            Rate = 1.5m,
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0fc45dce-14b9-4d76-bad0-92f8540ae109"),
                            Category = 4,
                            City = "Kaunas",
                            CreatedAt = new DateTime(2024, 2, 18, 20, 35, 32, 880, DateTimeKind.Utc).AddTicks(4150),
                            Rate = 1.2m,
                            StartDate = new DateTime(2024, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
